
export class Personnels{
  id:number;
  idE:number;
  cin: number;
  nom: string;
  prenom: string;
  civilite: string;
  signiature: string;
  genre: string;
  penseBete: string;
  idCU: number;
  adressePostale: string;
  fonction: string;
  email: string;
  creePar: number;
  modifiePar: number;
  createdAt:string;
  updatedAt:string;
  estAdmin:boolean;
  tel1:number;
  tel2:number;
  complement_adresse:string;
  ville:string;
  code_postal:string;
  avatar:any;
  affichClasses:string;
  messagerie:boolean;
  accueil:boolean;
  messagerieInt:boolean;
  messagerieExt:boolean;
  rdv:boolean;
  calendrierScol:boolean;
  docAdm:boolean;
  docAdmRenvoy:boolean;
  tabAff:boolean;
  galerie:boolean;
  emploi:boolean;
  reservation:boolean;
  cours:boolean;
  traveauxARendre:boolean;
  appelEnSalle:boolean;
  suivieJustif:boolean;
  saisieJustif:boolean;
  bilanAbsence:boolean;
  absencePersScol:boolean;
  sanctions:boolean;
  suivieEleves:boolean;
  notes:boolean;
  bilannotes:boolean;
  conseilClasse:boolean;
  bulletinsEleves:boolean;
  bulletinsclasses:boolean;
  infirmerie:boolean;
  dictionnaire:boolean;
  wiki:boolean;
  drive:boolean;
  office:boolean;
}

